---
title: "Lab_10"
author: "CP"
date: "`r Sys.Date()`"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos =c(CRAN = "http://cran.rstudio.com"))
```

```{r}
if (!require(RSQLite)) install.packages(c("RSQLite"))
if (!require(DBI))     install.packages(c("DBI"))                                

library(RSQLite)
library(DBI)


# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```
#```{r}

#PRAGMA table_info(actor)
#```

```{r}
dbGetQuery(con, "PRAGMA table_info(actor)")
```
Exercise 1
Retrive the actor ID, first name and last name for all actors using the actor table. Sort by last name and then by first name.



```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name")

```
```{r}
# clean up
dbDisconnect(con)
```

