---
title: "Lab 09"
author: "CP"
date: "`r Sys.Date()`"
output: 
  github_document:
    
    

always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Create a nxk matrix of poisson variables 

##Problem 2. 
```{r}
set.seed(1235)
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  
  return(x)
}
f1 <- fun1(1000, 4)
mean(f1)
```
```{r}
fun1alt <- function(n = 100, k = 4, lambda = 4) {
  # YOUR CODE HERE
  x <- matrix(rpois(n*k, lambda), ncol = 4) 
  return(x)
}

f1 <- fun1alt(50000, 4)
```


```{r}

#benchmarking
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)
```


### what is a matrix and what can we do with them 
```{r}
d <- matrix(1:16, ncol = 4)
d
```

## Problem 3. 

find the column max function max.col()

```{r}
diag(d)
d[c(1,6,11,16)]
d[cbind(1:4, 1:4)]
```
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
M <- matrix(runif(12), ncol=4)
M

# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
}
fun2(M)
fun2alt <- function(x) {
  # YOUR CODE HERE
 idx <- max.col( t(x))
 x[cbind(idx, 1:4)]
}
fun2alt(M)

# Benchmarking
x <- matrix(rnorm(1e4), nrow=10)
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)
```
```{r}
library(parallel)
 
```

```{r}
my_boot <- function(dat, stat, R, ncpus = 1L) {
  
  # Getting the random indices
  n <- nrow(dat)
  idx <- matrix(sample.int(n, n*R, TRUE), nrow=n, ncol=R)
 
  # Making the cluster using `ncpus`
  # STEP 1: GOES HERE
  cl <- makePSOCKcluster(4)
   clusterSetRNGStream(cl, 123)
  # STEP 2: GOES HERE
 clusterExport(cl,c("stat", "dat", "idx"))
  
    # STEP 3: THIS FUNCTION NEEDS TO BE REPLACES WITH parLapply
  ans <- parlapply(cl, seq_len(R), function(i) {
    stat(dat[idx[,i], , drop=FALSE])
  })
  
  # Coercing the list into a matrix
  ans <- do.call(rbind, ans)
  
  # STEP 4: GOES HERE
  
  ans
  
}
```

```{r}
my_stat <- function(d) coef(lm(y ~ x, data=d))

# DATA SIM
set.seed(1)
n <- 500; R <- 1e4

x <- cbind(rnorm(n)); y <- x*5 + rnorm(n)

# Checking if we get something similar as lm
ans0 <- confint(lm(y~x))
#ans1 <- my_boot(dat = data.frame(x, y), my_stat, R = R, ncpus = 2L)
#stopCluster(cl)

```

