---
title: "Assignment 01 - Exploratory Data Analysis"
author: "Camille Parchment"
date: "`r Sys.Date()`"
output: github_document
always_allow_html: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Step 1. 
##Read in the data 


```{r}
library(data.table)
library(tidyverse)
```
```{r}
epadf <- ("EPA_04.csv")
```

```{r}
class(epadf)
```
```{r}
epa19 <- fread("EPA_19.csv", header = TRUE, )
```
Checking head, tail,dimensions and summary for 2019 data. 

```{r}
summary(epa19)
```

```{r}
head(epa19)
```

```{r}
view(epa19)
```

```{r}
dim(epa19)

```
```{r}
tail(epa19)
```
```{r}
epa19[c(5,6,7,8,9,10), ]
```
Checking varibale names

```{r}
names(epa19)
```

```{r}
mean(epa19$`Daily Mean PM2.5 Concentration`)
```
Checking variable Type 

```{r}
class(epa19$Date)
class(epa19$POC)
class(epa19$DAILY_AQI_VALUE)
class(epa19$PERCENT_COMPLETE)
class(epa19$CBSA_CODE)
class(epa19$STATE)
class(epa19$SITE_LATITUDE)
class(epa19$Source)
class(epa19$`Daily Mean PM2.5 Concentration`)
class(epa19$`Site Name`)
class(epa19$AQS_PARAMETER_CODE)
class(epa19$CBSA_NAME)
class(epa19$COUNTY_CODE)
class(epa19$SITE_LONGITUDE)
class(epa19$`Site ID`)
class(epa19$UNITS)
class(epa19$DAILY_OBS_COUNT)
class(epa19$AQS_PARAMETER_DESC)
class(epa19$COUNTY)

```









