---
title: "Assignment_4"
author: "CP"
date: "`r Sys.Date()`"
output: html_document
always_allow_html: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```

```{r}
library(RSQLite)
library(DBI)

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
film <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/film.csv")
film_category <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/film_category.csv")
category <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/category.csv")

# Copy data.frames to database
dbWriteTable(con, "film", film)
dbWriteTable(con, "film_category", film_category)
dbWriteTable(con, "category", category)
```
```{r}
dbGetQuery(con, "PRAGMA table_info(category)")
```


```{sql, connection=con, output.var = "x1"}
PRAGMA table_info(film)

```

## Question 1
How many many movies is there avaliable in each rating catagory.

```{r}
dbGetQuery(con,"
SELECT  rating, COUNT(*) AS count
FROM  film
GROUP BY rating
")
```

## Question 2
What is the average replacement cost and rental rate for each rating category.
```{r}
dbGetQuery(con,"
SELECT  rating, replacement_cost, rental_rate,
COUNT(*) AS count,
AVG(replacement_cost) AS avgreplacement_cost
FROM  film
GROUP BY rating
")
```

## Question 3
Use table film_category together with film to find the how many films there are with each category ID

```{r}

```

