---
title: "Assignment_02"
author: "Camille Parchment"
date: "`r Sys.Date()`"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!file.exists("individual.csv"))
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/01_chs/chs_individual.csv", "individual.csv", method="libcurl", timeout = 60)
```
```{r}
indv <- read.csv("individual.csv")
```

```{r}
if (!file.exists("regional.csv"))
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/01_chs/chs_regional.csv", "regional.csv", method="libcurl", timeout = 60)
```
```{r}
reg <- read.csv("regional.csv")
```

### Merge data 

```{r}
chs <- merge(indv, reg, by="townname")
```
```{r}
nrow(chs)
```

After merging based on  location (townname) there are still 1200 observations in our data set.

```{r}
library(tidytext)
library(tidyverse)
library(data.table)
library(dplyr)
library(ggplot2)
```
```{r}
chs <- as_tibble(chs)
```
```{r}
library(dtplyr)
```

### Create a BMI catergorical variable and a summary table with underweight, normal weight, overweight, and obese. 

```{r}
obesity_level <- cut(chs$bmi, breaks=c(0, 14, 22, 24, 100), labels= c("underweight","normal", "overwight","obese"), right = FALSE)
```
```{r}
obesity_level[1:10]
```
```{r}
chs$bmi[1:10]
```
```{r}
summary(obesity_level) 
```
```{r}
summary(chs$bmi, na.rm = TRUE)
```
```{r}
smoke_gas_exposure <- mutate(chs,)
```


```{r}
smoke_gas_exposure <-  ifelse(chs$smoke == 0 | chs$gasstove == 0 , "none", 
                              ifelse(chs$smoke == 1, "smoke_only",
                              ifelse(chs$gasstove == 1, "gas_only", smoke_gas_exposure)))
```
 
```{r}
table(smoke_gas_exposure)
```

